export const USER_SCHEMA_NAME = 'user'
export const SERVICE_SCHEMA_NAME = 'service'
export const PRODUCT_SCHEMA_NAME = 'product'
export const CUSTOMER_SCHEMA_NAME = 'customer'
export const APPOINTMENT_SCHEMA_NAME = 'appointment'
export const PARTNERSHIP_SCHEMA_NAME = 'partnership'
export const API_KEY_SCHEMA_NAME = 'apiKey'
export const SETTINGS_SCHEMA_NAME = 'setting'